config:
  - key: config/services/builds/protocols/http/host
    value: active.builds

  - key: config/services/builds/protocols/http/port
    value: 8080

  - key: config/services/builds/protocols/http/virtualdirectory
    value: builds

  - key: config/services/builds/url/proxy
    value: http://infrastructure.calvinverse.net/builds

  - key: config/services/queue/builds/vhost
    value: vhost.build.trigger
